set -g base-index 1
setw -g pane-base-index 1

set -g mouse on

# Use C-h/j/k/l to switch panes
# bind-key -n C-h select-pane -L
# bind-key -n C-j select-pane -D
# bind-key -n C-k select-pane -U
# bind-key -n C-l select-pane -R

## vim-tmux-navigator plugin
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'

## use terminals colors, transparency, etc
set-option -g status-style bg=default

## better split bindings
bind h split-window -v -c "${pane_current_path}"
bind v split-window -h -c "${pane_current_path}"

## Kill pane with no confirm
bind-key x kill-pane
